---
- name: Create a GCP instance
  hosts: localhost
  vars:
    gcp_project: cps-sandbox-231416
    gcp_cred_kind: serviceaccount
    gcp_cred_file: "/Users/dave.ellis/SSH/cps-sandbox-231416-3865c88ffeb0.json"
    task_state: "absent"
  tasks:
    - name: create a disk
      gcp_compute_disk:
        name: dave-disk-instance
        size_gb: 50
        source_image: projects/rhel-cloud/global/images/rhel-7-v20210721
        zone: us-central1-a
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: "{{ task_state }}"
      register: disk

   # - name: create a network
   #   gcp_compute_network:
   #     name: davenetwork
   #     project: "{{ gcp_project }}"
   #     auth_kind: "{{ gcp_cred_kind }}"
   #     service_account_file: "{{ gcp_cred_file }}"
   #     state: present
   #   register: network

    - name: create an address
      gcp_compute_address:
        name: dave-address-instance
        region: us-central1
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: "{{ task_state }}"
      register: address

    - name: create a instance
      gcp_compute_instance:
        name: daveansibletest
        machine_type: n1-standard-1
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        network_interfaces:
        - network:
          access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
        zone: us-central1-a
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: "{{ task_state }}"